return {
	ANNOUNCE_ADVENTUREFAIL = "不.. 不 能 在 这 里 失 败..",
	ANNOUNCE_BOOMERANG = "这 个 笨 蛋 木 棍!",
	ANNOUNCE_CHARLIE = "我 不 怕 你! 皇 冠 是 我 的!",
	ANNOUNCE_CHARLIE_ATTACK = "哎 呀! 别 再 躲 着 了!",
	ANNOUNCE_COLD = "啊! 我 的 手 指 被 冻 伤 了!",
	ANNOUNCE_HOT = "这 真 是 太 热 了!",
	ANNOUNCE_DUSK = "夜 晚 快 要 来 临 了..",
	ANNOUNCE_EAT =
	{
		GENERIC = "味 道 真 好!",
		PAINFUL = "唔!",
		SPOILED = "像 皮 弗 娄 牛 粪 便 的 味 道!",
		STALE = "啧!",
	},
	ANNOUNCE_HOUNDS = "出 来 和 我 打 一 场!",
	ANNOUNCE_HUNGRY = "肚 子 太 饿 了..",
	ANNOUNCE_HUNT_BEAST_NEARBY = "正 在 接 近!",
	ANNOUNCE_HUNT_LOST_TRAIL = "已 经 失 去 气 味 了.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "嘘.. 我 找 不 到 它 的 气 味 了.",
	ANNOUNCE_ACCOMPLISHMENT= "没 有 谁 可 以 夺 走 我 的 皇 冠!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "我 不 会 停 止 的!",	
	ANNOUNCE_PECKED = "喂! 别 闹 了，笨 蛋!",
	ANNOUNCE_TORCH_OUT = "火 炬 熄 灭 了!",
	ANNOUNCE_WORMHOLE = "唔... 那 个 东 西 太 恶 心 了!",
	ANNOUNCE_TRAP_WENT_OFF = "呀!",
    ANNOUNCE_CRAFTING_FAIL = "嗯. 缺 少 什 么 东 西 呢?",
    ANNOUNCE_QUAKE = "全 部 都 在 震 动!",
    ANNOUNCE_NODANGERSLEEP = "现 在 不 能 睡 觉, 要 小 心.",
    ANNOUNCE_NOHUNGERSLEEP = "啊！ 太饿了.. 我 的 床 看 起 来 真 好 吃.",
    ANNOUNCE_FREEDOM = "哈! 你 不 能 阻 止 我!",
    ANNOUNCE_RESEARCH = "要 是 再 多 点 就 好 了.",
    ANNOUNCE_NO_TRAP = "偷 偷 摸 摸 的 我 又 赢 了!",
    ANNOUNCE_HIGHRESEARCH = "哦.. 我 的 头 变 大 了?",
    ANNOUNCE_THORNS = "哦! 粗 鲁 的 植 物!",
    ANNOUNCE_NODAYSLEEP_CAVE = "我 不 能 在 这 儿 睡 觉, 它 让 我 的 皮 肤 不 舒 服.",
    ANNOUNCE_BEES = "蜜 蜂 出 错 了!",
    ANNOUNCE_KNOCKEDOUT = "欧.. 有 星 星 在 旋 转..",
    ANNOUNCE_LOWRESEARCH = "我 喜 欢 那 一 个, 它 有 图 片.",
    ANNOUNCE_DEERCLOPS = "嗯. 我 的 鼻 子 说 很 危 险!",
    ANNOUNCE_MOSQUITOS = "我 要 把 你 咬 回 来, 疯 子!",
    ANNOUNCE_NODAYSLEEP = "睡 觉? 我 想 要 去 奔 跑!",
    ANNOUNCE_INSUFFICIENTFERTILIZER = "猜 猜 这 植 物 好 不 好 吃..",
	ANNOUNCE_CANFIX = "\n我 觉 得 我 能 修 好 这 个!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "这 让 我 高 兴 不 起 来.",
	BATTLECRY =
	{
		GENERIC = "来 和 我 打 啊!",
		PIG = "把 你 变 成 肉 干!",
		PREY = "唔 啊!",
		SPIDER = "揍 扁 你!",
		SPIDER_WARRIOR = "攻 击!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "我 也 是 这 么 想 的!",
		PIG = "嘿! 回 到 这 儿 来!",
		PREY = "下 次 再 找 你 算 账!",
		SPIDER = "口 水 直 流!",
		SPIDER_WARRIOR = "逃 跑 的 小 虫 子!",
	},
	DESCRIBE =
	{
		GLOWDUST ="吃 的 时 候 我 想 起 了 作 者!",
		MUSHA_EGG ="好暖和.. 大 概 可 以 孵 出 来.",
		MUSHA_EGG1 ="小 家 伙 正 准 备 冒 险?",
		MUSHA_EGG2 ="似 乎 有 点 抖 动..",
		MUSHA_EGG3 ="走! 走! 去 冒 险!",
		MUSHA_SMALL ="噢, 太 可 爱 了!",
		MUSHA_TEEN ="长 大 了 也 这 么 可 爱 呢!",
		MUSHA_TALL ="是 啊! 健 康 地 成 长",
		MUSHA_TALL2 ="它 看 起 来 有 足 够 的 战 斗 力..",
		MUSHA_TALL3 ="也 许 这 火 焰 是 它 身 体 发 出 的?",
		MUSHA_TALL4 ="哇! 变 得 好...好 大！",
		MUSHA_TALL5 = "它 是 一 个 强 力 的 伙 伴!",
		GHOSTHOUND = "古 代 的 狗, 保 护 我 !",
		MUSHA_FLUTE = "Yamche 喜 欢 听 我 的 曲 子",

        BOOK_BIRDS = "鸟 声 的 解 释.",
        BOOK_TENTACLES = "黏 糊 糊 东 西 的 秘 密.",
        BOOK_GARDENING = "提 升 植 物 的 能 力",
        BOOK_SLEEP = "一 个 很 无 聊 的 书.",
        BOOK_BRIMSTONE = "不 是 一 本 好 书..",

		WORMLIGHT = "好 漂 亮! 我 能 拿 它 吗?",
		WORM =
		{
		    PLANT = "哦.. 看 那 个!",
		    DIRT = "这 气 味 不 正 确.",
		    WORM = "啊! 杀 了 它!",
		},
		EEL = "唔, 黏 糊 糊 的!",
		EEL_COOKED = "我 对 它 没 什 么 兴 趣.",
		UNAGI = "没 想 到 这 可 以 吃.",
		EYETURRET = "它 打 我!",
		EYETURRET_ITEM = "喂, 你 在 做 什 么!",
		MINOTAURHORN = "太 强 大 了!",
		MINOTAURCHEST = "想 想 宝 物!",
		THULECITE_PIECES = "把 这 些 碎 片 拼 在 一 起.",
		POND = "没 有 时 间 洗 澡 了.",
		POND_ALGAE = "呼. 没 有 火 鸡 躲 在 这 儿.",
		GREENSTAFF = "感 觉 真 不 可 思 议.",
		POTTEDFERN = "有 个 小 房 子 的 植 物.",

		THULECITE = "感 觉 不 灵 了, 嗅 觉 不 灵 了.. 味 觉 也 不 灵!",
		ARMORRUINS = "虽 然 很 轻 但 是 很 强!",
		RUINS_BAT = "感 觉 不 止 一 个.",
		RUINSHAT = "我 不 应 该 戴 别 人 的 皇 冠..",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "看 起 来 很 正 常.",	--Calm phase
			WARN = "那 有 一 点 光 芒.",	--Before nightmare
			WAXING = "它 开 始 了!", --Nightmare Phase first 33%
			STEADY = "我 能 感 觉 到 振 动!", --Nightmare 33% - 66%
			WANING = "它 平 静 下 来 了.", --Nightmare 66% +
			DAWN = "又 走 了 一 遍 黑 暗", --After nightmare
			NOMAGIC = "没 有 什 么 不 正 常.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "他 在 这 儿 多 久 了?",
		ROOK_NIGHTMARE = "我 一 点 都 不 喜 欢 这 点 儿.",
		KNIGHT_NIGHTMARE = "看 起 来 很 累 了.",
		MINOTAUR = "这 是 真 的 牛 头 怪 吗?",	--Monster in labyrinth
		SPIDER_DROPPER = "别 碰 我 的 头 发!",	--White spider that comes from the roof
		NIGHTMARELIGHT = "这 些 光 让 我 的 眼 睛 好 疼.",	--Lights that activate during nightmare.
		GREENGEM = "苹 果 的 味 道. 感 觉 很 轻.",
		RELIC = "没 有 气 味, 已 经 很 久 了.",	--Fixed relic
		RUINS_RUBBLE = "有 什 么 部 件 不 见 了.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "我 的 发 明 真 可 怕!",	--Works as axe and pickaxe
		ORANGESTAFF = "这 真 有 趣!",	--Teleports player.
		YELLOWAMULET = "闪 闪 发 光!",	--Emits light, player walks faster.
		GREENAMULET = "教 我 更 好 的 组 合 东 西.",	--Reduce cost of crafting

		SLURPER = "唔! 什 么 味 道?",
		SLURPER_PELT = "气 味 更 难 闻 了..",
		ARMORSLURPER = "额........!",
		ORANGEAMULET = "现 在 我 可 以 休 息 一 下 了.",
		YELLOWSTAFF = "如 此 明 亮!",
		YELLOWGEM = "我 最 喜 欢 黄 色 的 了!",
		ORANGEGEM = "不 是 橘 子. 没 有 橘 子 的 味 道.",
		TELEBASE = 
		{
			VALID = "啊! 有 效 了!",
			GEMS = "缺 少 了 什 么?",
		},
		GEMSOCKET = 
		{
			VALID = "宝 石 比 什 么 都 好!",
			GEMS = "掉 了 一 点?",
		},
		STAFFLIGHT = "更 多! 更 多!",
		RESEARCHLAB4 = "这 不 是 工 作 的 帽 子.",
	
        ANCIENT_ALTAR =
        {
        	WORKING = "你 能 听 到 我 的 鬼 叫?",
        	BROKEN = "感 觉 很 冷.",
        },  
  
        ANCIENT_STATUE = "哦, 真 难 看.",

        LICHEN = "只 是 苔 藓.",
		CUTLICHEN = "唔! 我 为 什 么 要 吃 植 物?",

        CAVE_BANANA = "..这 是 个 错 误 吗?",
        CAVE_BANANA_COOKED = "哦! 神 秘 的 食 物!",
        CAVE_BANANA_TREE = "好 酷 的 树!",
        ROCKY = "这 个 岩 石 还 活 着!",

        BLUEAMULET = "啊! 窝 的 涩 逗 不 听 斯 唤 了!",
		PURPLEAMULET = "这 给 我 不 好 的 感 觉..",
		TELESTAFF = "他 们 要 去 哪?",
		MINERHAT = "就 像 一 个 专 业 的!",
		MONKEY = "臭 毛 皮 兽!",
		MONKEYBARREL = "毛 皮 和 粪 便 的 气 味.",

		HOUNDSTOOTH="我 的 牙 齿 很 小 的..",
		ARMORSNURTLESHELL="我 可 以 在 这 里 睡 觉 吗?",
		BAT="毛 茸 茸 的 虫 子!",
		BATBAT = "打 错 了 蝙 蝠!",
		BATWING="唔哇哇哇.. 我 不 能 飞.",
		BATWING_COOKED="美 味 的!",
		BEDROLL_FURRY="哦, 好 舒 服!",
		BUNNYMAN="哦，他 们 看 起 来 很 好 吃..",
		FLOWER_CAVE="最 好 的 植 物 朋 友!",
		FLOWER_CAVE_DOUBLE="最 好 的 植 物 朋 友!",
		FLOWER_CAVE_TRIPLE="最 好 的 植 物 朋 友!",
		GUANO="他 们 没 有 洗 澡 的 地 方 吗?",
		LANTERN="比 火 炬 更 好.",
		LIGHTBULB="它 怎 么 发 光 的?",
		MANRABBIT_TAIL="蓬 松 的 绒 毛!",
		MUSHTREE_TALL="我 也 可 以 变 大 吗?",
		MUSHTREE_MEDIUM="打 扮 花 哨 的 蘑 菇.",
		MUSHTREE_SMALL="它 不 是 糖 果 做 的, 我 吃 过!",
		RABBITHOUSE="这 里 是 吃 晚 餐 的 地 方.",
		SLURTLE="有 壳 的 臭 虫!",
		SLURTLE_SHELLPIECES="啊, 打 破 它.",
		SLURTLEHAT="现 在 我 也 有 壳 了!",
		SLURTLEHOLE="谁 在 那?",
		SLURTLESLIME="唔, 粘 液!",
		SNURTLE="快 回 来! 我 一 点 儿 也 不 可 怕!",
		SPIDER_HIDER="它 有 盔 甲!",
		SPIDER_SPITTER="唔 哇, 好 多 的 蜘 蛛!",
		SPIDERHOLE="全 是 蜘 蛛 网.",
		STALAGMITE="一 座 小 型 的 山!",
		STALAGMITE_FULL="一 座 小 型 的 山!",
		STALAGMITE_LOW="一 座 小 型 的 山!",
		STALAGMITE_MED="一 座 小 型 的 山!",
		STALAGMITE_TALL="一 座 小 型 的 山!",
		STALAGMITE_TALL_FULL="一 座 小 型 的 山!",
		STALAGMITE_TALL_LOW="一 座 小 型 的 山!",
		STALAGMITE_TALL_MED="一 座 小 型 的 山!",
		-- Crafted floor items
		TURF_CARPETFLOOR = "地 面 真 无 聊.",
		TURF_CHECKERFLOOR = "地 面 真 无 聊.",
		TURF_DIRT = "地 面 真 无 聊.",
		TURF_FOREST = "地 面 真 无 聊.",
		TURF_GRASS = "地 面 真 无 聊.",
		TURF_MARSH = "地 面 真 无 聊.",
		TURF_ROAD = "地 面 真 无 聊.",
		TURF_ROCKY = "地 面 真 无 聊.",
		TURF_SAVANNA = "地 面 真 无 聊.",
		TURF_WOODFLOOR = "地 面 真 无 聊.",

		TURF_CAVE="地 面 真 无 聊.",
		TURF_FUNGUS="地 面 真 无 聊.",
		TURF_SINKHOLE="地 面 真 无 聊.",
		TURF_UNDERROCK="地 面 真 无 聊.",
		TURF_MUD="地 面 真 无 聊.",

		TURKEYDINNER = "现 在 我 要 吃 火 鸡!",
		TWIGS = "树 枝!",
		POWCAKE = "我 不 知 道 这 是 不 是 食 物..",
        CAVE_ENTRANCE = 
        {
            GENERIC="堵 住 洞 穴 的 石 头.",
            OPEN = "看 起 来 好 暗..",
        },
        CAVE_EXIT = "回 到 有 光 的 地 方 了!",

		MAXWELLPHONOGRAPH = "我 想 要 快 乐 的 音 乐!",
		PIGGUARD = "脾 气 暴 躁 的 小 猪.",
		BOOMERANG = "一 根 可 以 自 己 回 来 的 棍 子!",
		ADVENTURE_PORTAL = "更 多 的 冒 险!",
		AMULET = "让 我 感 觉 更 安 全.",
		ANIMAL_TRACK = "*吸...* 我 可 以 跟 踪 他.",
		ARMORGRASS = "夏 天 的 衣 服!",
		ARMORMARBLE = "石 头 做 成 的 衣 服?",
		ARMORWOOD = "它 是 木 片 做 的.",
		ARMOR_SANITY = "它 是 真 实 的 吗?",
		ASH =
		{
			GENERIC = "火 烧 毁 了 这 一 切.",
			REMAINS_EYE_BONE = "烧 掉 了!",
			REMAINS_THINGIE = "它 现 在 没 有 了..",
		},
		AXE = "生 存 的 第 一 个 工 具!",
		BABYBEEFALO =
		{
			GENERIC = "小 不 点!.",
			SLEEPING = "它 在 打 呼 噜",
		},
		BACKPACK = "房 间 里 的 东 西!",
		BACONEGGS = "嗯，肉 和 蛋!",
		BANDAGE = "包 扎 伤 口.",
		BASALT = "很 坚 固 的 石 头!",
		BEARDHAIR = "谁 的 毛 发?",
		BEDROLL_STRAW = "哦~, 我 喜 欢 午 睡.",
		BEE =
		{
			GENERIC = "嗡 嗡 的 昆 虫!",
			HELD = "好 好 呆 在 那.",
		},
		BEEBOX =
		{
			GENERIC = "蜜 蜂 的 房 子!",
			READY = "里 面 都 是 蜜 蜂!",
		},
		BEEFALO =
		{
			FOLLOWER = "我 比 皮 弗 娄 牛 好 闻 吗?",
			GENERIC = "哦.. 看 着 它 们 我 都 饿 了.",
			NAKED = "愚 蠢 的 皮 弗 娄 牛.",
			SLEEPING = "它 看 起 来 很 安 逸.",
		},
		BEEFALOHAT = "好 痒!",
		BEEFALOWOOL = "好 厚, 好 痒.",
		BEEHIVE = "太 吵 了.",
		BEEMINE = "它 们 被 关 在 里 面 会 很 生 气 的.",
		BEEMINE_MAXWELL = "我 要 给 你 们 一 个 教 训!.",
		BEEHAT = "现 在 我 可 以 和 嗡 嗡 的 虫 子 玩 了!",
		BERRIES = "我 把 它 们 当 成 糖 果.",
		BERRIES_COOKED = "不.. 还 是 浆 果.",
		BERRYBUSH =
		{
			BARREN = "这 个 浆 果 丛 需 要 努 力 工 作.",
			WITHERED = "噢，它 枯 萎 了.",
			GENERIC = "看 起 来 不 错 的 浆 果.",
			PICKED = "嘘. 都 过 去 了.",
		},
		BIRDCAGE =
		{
			GENERIC = "一 个 新 朋 友 的 地 方!",
			OCCUPIED = "呆 在 那!",
			SLEEPING = "噢. 她 把 头 放 在 翅 膀 下 面 睡 觉!",
		},
		BIRDTRAP = "小 鸟 在 里 面. 它 出 不 来 了!",
		BIRD_EGG = "包 装 食 品!",
		BIRD_EGG_COOKED = "真 美 味!",
		BISHOP = "机 器 人?",
		BLOWDART_FIRE = "必 须 小 心 点!",
		BLOWDART_SLEEP = "瞬 间 睡 着 了.",
		BLOWDART_PIPE = "我 是 忍 者!",
		BLUEGEM = "像 蓝 色 的 海 洋!",
		BLUEPRINT = "噢.. 我 的 方 法 是 错 的!",
		BLUE_CAP = "蓝 色 是 健 康 的.",
		BLUE_CAP_COOKED = "烧 熟 的 味 道 更 好!",
		BLUE_MUSHROOM =
		{
			GENERIC = "我 要 砍 蘑 菇 树.",
			INGROUND = "偷 偷 摸 摸 的 蘑 菇!",
			PICKED = "等 它 们 重 新 长 出 来?",
		},
		BOARDS = "我 现 在 是 木 匠!",
		BONESTEW = "这 是 食 物 的 全 部 份 量!",
		BUGNET = "一 个 不 漏!",
		BUSHHAT = "灌 木 丛 做 的 帽 子.",
		BUTTER = "下 午 茶!",
		BUTTERFLY =
		{
			GENERIC = "这 是 个 振 翅 的 虫 子.",
			HELD = "喉 咙 发 痒!",
		},
		BUTTERFLYMUFFIN = "蝴 蝶 蛋 糕? 我 不 知 道.",
		BUTTERFLYWINGS = "噢, 可 怜 的 蝴 蝶.",
		CAMPFIRE =
		{
			EMBERS = "接 近 了.",
			GENERIC = "火 吗? 是 火!",
			HIGH = "哦~.. 烤 面 包.",
			LOW = "没 有 更 高 的 温 度..",
			NORMAL = "耶, 棉 花 糖 的 时 间!",
			OUT = "需 要 更 多 的 燃 料.",
		},
		CANE = "散 步 的 时 间!",
		CARROT = "橙 子 的 亲 戚.",
		CARROT_COOKED = "噢.. 蔬 菜..",
		CARROT_PLANTED = "我 能 看 见 你!",
		CARROT_SEEDS = "小 胡 萝 卜!",
		CAVE_FERN = "你 也 要 一 个 锅 吗?",
		CHARCOAL = "再 见！树 先 生!",
        CHESSJUNK1 = "只 是 现 在 很 少.",
        CHESSJUNK2 = "这 太 恐 怖 了..",
        CHESSJUNK3 = "他 死 了? 很 好.",
		CHESTER = "我 喜 欢 它 的 角!",
		CHESTER_EYEBONE =
		{
			GENERIC = "..看 起 来 很 好 吃.",
			WAITING = "没 有 做 太 多.",
		},
		COOKEDMEAT = "耶!",
		COOKEDMONSTERMEAT = "嗯, 味 道 不 错.",
		COOKEDSMALLMEAT = "喔.. 能 给 我 更 大 一 点 吗?",
		CORN = "如 果 你 是 小 鸟.",
		CORN_COOKED = "火 弄 坏 了 它!",
		CORN_SEEDS = "鸟 的 食 物.",
		CROW =
		{
			GENERIC = "你 好,小 鸟!",
			HELD = "我 抓 到 你 了!",
		},
		CUTGRASS = "柔 软 但 是 很 坚 韧.",
		CUTREEDS = "比 草 还 坚 韧.",
		CUTSTONE = "我 要 做 个 城 堡!",
		DEADLYFEAST = "闻 起 来 都 不 好.",
		DEERCLOPS = "..我 要 走 了, 再 见!",
		DEERCLOPS_EYEBALL = "我 不 想 碰 它!",
		DIRTPILE = "我 发 现 了 什 么!",
		DIVININGROD =
		{
			COLD = "哦, 它 发 出 了 声 音!",
			GENERIC = "这 是 个 奇 怪 的 棒 子.",
			HOT = "棒 子 现 在 很 安 静!",
			WARM = "发 出 了 更 多 的 声 音!",
			WARMER = "哔 哔 哔 哔 哔!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "嗯? 这 是 什 么?",
			READY = "它 需 要 什 么 东 西?",
			UNLOCKED = "正 在 运 行!",
		},
		DIVININGRODSTART = "还 需 要 其 他 的 东 西!",

		DRAGONFRUIT = "哇, 好 酷 的 水 果!",
		DRAGONFRUIT_COOKED = "嗯，闻 起 来 是 甜 的.",
		DRAGONFRUIT_SEEDS = "我 能 变 成 龙 吗?",
		DRAGONPIE = "甜 点 水 果 馅 饼.",
		DRUMSTICK = "有 把 手 的 肉!",
		DRUMSTICK_COOKED = "吃 了 你? 好 呀!",
		DURIAN = "杀 了 它!",
		DURIAN_COOKED = "它 死 了. 很 好.",
		DURIAN_SEEDS = "不, 不 要 长 出 更 多 了!",
		EARMUFFSHAT = "看 起 来 很 酷, 感 觉 有 点 暖.",
		EGGPLANT = "这 是 鸡 蛋 吗?",
		EGGPLANT_COOKED = "这 里 没 有 鸡 蛋, 只 有 素 食.",
		EGGPLANT_SEEDS = "告 诉 我 怎 么 分 开 它? 闻 气 味 吗!",
		STUFFEDEGGPLANT = "食 物 越 多 越 好.",
		DUG_BERRYBUSH = "这 真 不 幸.",
		DUG_GRASS = "它 不 开 心 了.",
		DUG_MARSH_BUSH = "它 很 不 幸.",
		DUG_SAPLING = "它 很 不 幸.",
		EARMUFFS = "看 起 来 很 酷, 感 觉 有 点 暖.", -- Unused?
		DECIDUOUSTREE = 
		{
			BURNING = "可 怜 的 树.",
			BURNT = "它 不 会 再 生 长 了..",
			CHOPPED = "对 不 起!",
			GENERIC = "只 是 一 棵 树.",
		},
		ACORN = 
		{
		    GENERIC = "树 的 宝 宝!",
		    PLANTED = "看 起 来 是 个 无 聊 的 树.",
		},
		EVERGREEN =
		{
			BURNING = "可 怜 的 树.",
			BURNT = "它 不 会 再 生 长 了..",
			CHOPPED = "对 不 起!",
			GENERIC = "只 是 一 棵 树.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "可 怜 的 树.",
			BURNT = "它 不 会 再 生 长 了..",
			CHOPPED = "对 不 起!",
			GENERIC = "只 是 一 棵 树.",
		},
		EYEPLANT = "啊哈! 证 明 蔬 菜 都 是 邪 恶 的!",
		FARMPLOT =
		{
			GENERIC = "土 地 是 我 的!",
			GROWING = "加 油 ，加 油, 生 长 ，生 长!",
			NEEDSFERTILIZER = "感 觉 肚 子 饿 了.",
		},
		FEATHERHAT = "伪 装 成 鸟!",
		FEATHER_CROW = "乌 鸦 的 羽 毛. 真 漂 亮.",
		FEATHER_ROBIN = "红 鸟 的 羽 毛. 真 漂 亮.",
		FEATHER_ROBIN_WINTER = "雪 鸟 的 羽 毛. 真 漂 亮.",
		FEM_PUPPET = "她 闻 起 来 不 对 劲.",
		FIREFLIES =
		{
			GENERIC = "耶, 美 丽 的 错 误!",
			HELD = "太 酷 了!",
		},
		FIREHOUND = "你 的 火 不 会 打 败 我 的!",
		FIREPIT =
		{
			EMBERS = "接 近 了.",
			GENERIC = "火 吗? 是 火!",
			HIGH = "哦~.. 太 温 暖 了.",
			LOW = "没 有 更 高 的 温 度 了..",
			NORMAL = "耶, 软 糖 的 时 间!",
			OUT = "需 要 更 多 的 燃 料.",
		},
		FIRESTAFF = "我 只 烧 了 一 点 东 西, 真 的.",
		FISH = "双 面 软 碟.",
		FISHINGROD = "抓 住 鱼 的 鳍.",
		FISHSTICKS = "一 口 这 么 大.",
		FISHTACOS = "方 便 携 带 的 食 物!",
		FISH_COOKED = "有 条 纹 的.",
		FLINT = "锋 利 的 石 头.",
		FLOWER = "万 岁!",
		FLOWERHAT = "带 给 我 好 运.",
		FLOWER_EVIL = "啊 唔! 你 闻 到 了 什 么!",
		FOLIAGE = "少 量 的 植 物.",
		FOOTBALLHAT = "闻 起 来 像 猪 头.",
		FROG =
		{
			DEAD = "它 真 粗 鲁.",
			GENERIC = "跳   跳   跳.",
			SLEEPING = "错 误 的 梦 想.",
		},
		FROGGLEBUNWICH = "看 起 来 准 备 跳 了.",
		FROGLEGS = "太 黏 了.",
		FROGLEGS_COOKED = "现 在 闻 起 来 好 了.",
		FRUITMEDLEY = "水 果!",
		GEARS = "让 东 西 可 以 运 转.",
		GHOST = "没 有 发 出 气 味!",
		GOLDENAXE = "有 钱 一 切 好 办!",
		GOLDENPICKAXE = "有 钱 一 切 好 办!",
		GOLDENPITCHFORK = "有 钱 一 切 好 办!",
		GOLDENSHOVEL = "有 钱 一 切 好 办!",
		GOLDNUGGET = "我 的 皇 家 银 行.",
		GRASS =
		{
			BARREN = "想 要 植 物 做 的 食 物.",
			WITHERED = "它 干 枯 了.",
			BURNING = "火!",
			GENERIC = "草, 不 好 吃.",
			PICKED = "不 够 抓 取",
		},
		GREEN_CAP = "让 你 很 头 晕.",
		GREEN_CAP_COOKED = "现 在 闻 起 来 好 了.",
		GREEN_MUSHROOM =
		{
			GENERIC = "我 继 续 看 蘑 菇 树.",
			INGROUND = "偷 偷 摸 摸 的 蘑 菇!",
			PICKED = "等 它 们 长 大?",
		},
		GUNPOWDER = "要 非 常 小 心..",
		HAMBAT = "这 也 是 个 点 心.",
		HAMMER = "可 以 拆 东 西.",
		HEALINGSALVE = "又 粘 又 臭.",
		HEATROCK =
		{
			FROZEN = "冷 得 像 冰!",
			COLD = "摸 着 好 冷.",
			GENERIC = "平 常 的 石 头.",
			WARM = "舒 服.",
			HOT = "温 暖!",
		},
		HOMESIGN = "我 不 会 认 标 志, 闻 闻 就 可 以 了.",
		HONEY = "让 人 感 到 甜 蜜 的 东 西!",
		HONEYCOMB = "怎 么 生 产 蜜 蜂 的?",
		HONEYHAM = "有 肉 和 蜂 蜜, 真 好 吃!",
		HONEYNUGGETS = "亲 爱 的 点 心.",
		HORN = "嘟~ 嘟~ 嘟~",
		HOUND = "我 咬!",
		HOUNDMOUND = "召 集 它 们 的 房 子?",
		HOUNDBONE = "让 我 有 点 饿 了.",
		ICEBOX = "里 面 可 以 保 存 食 物.",
		ICEHOUND = "它 结 霜 了",
		INSANITYROCK =
		{
			ACTIVE = "我 搞 不 清 楚 了.",
			INACTIVE = "石 头?",
		},
		JAMMYPRESERVES = "果 酱, 劣 质 蜂 蜜.",
		KABOBS = "把 肉 和 骨 头 串 起 来 携 带.",
		KILLERBEE =
		{
			GENERIC = "看 起 来 是 蜜 蜂.",
			HELD = "你 没 刺 到 我!",
		},
		KNIGHT = "我 可 以 带 走 它.",
		KOALEFANT_SUMMER = "喔~~~~...............!",
		KOALEFANT_WINTER = "它 看 起 来 真 的 很 温 暖..",
		KRAMPUS = "这 个 混 蛋!",
		KRAMPUS_SACK = "现 在 是 我 的.",
		LEIF = "树 在 走 路!",
		LEIF_SPARSE = "树 在 走 路!",
		LIGHTNING_ROD =
		{
			CHARGED = "这 让 我 汗 毛 直 竖!",
			GENERIC = "它 在 工 作?",
		},
		LITTLE_WALRUS = "我 一 个 人 离 开!",
		LIVINGLOG = "慢 慢 打 起 精 神.",
		LOCKEDWES = "他 需 要 帮 助.",
		LOG =
		{
			BURNING = "不 会 烧 太 长.",
			GENERIC = "不 知 为 何，树 就 这 样 长 出 来 了.",
		},
		LUREPLANT = "愚 蠢 的 植 物. 我 的 鼻 子 不 会 骗 我 的.",
		LUREPLANTBULB = "可 以 做 个 好 陷 阱.",
		MALE_PUPPET = "他 闻 起 来 不 对 劲.",
		MANDRAKE =
		{
			DEAD = "现 在 很 奇 怪 了..",
			GENERIC = "奇 怪 的 植 物.",
			PICKED = "我 不 想 碰 它.",
		},
		COOKEDMANDRAKE = "它 看 着 我!",
		MANDRAKESOUP = "幽 灵 的 问 题 解 决 了.",
		MARBLE = "石 头 版 的 糖 果.",
		MARBLEPILLAR = "有 人 雕 过 它.",
		MARBLETREE = "坚 硬 的 树.",
		MARSH_BUSH =
		{
			BURNING = "它 不 是 很 好.",
			GENERIC = "长 刺 的 植 物.",
			PICKED = "噢~.",
		},
		MARSH_PLANT = "只 是 一 个 小 小 的 植 物.",
		MARSH_TREE =
		{
			BURNING = "我 不 喜 欢 这 个.",
			BURNT = "它 不 会 再 长 了..",
			CHOPPED = "斧 头 砍 掉 刺.",
			GENERIC = "看 起 来 像 是 树.",
		},
		MAXWELL = "他 想 做 什 么?",
		MAXWELLHEAD = "他 确 实 很 想 说 话.",
		MAXWELLLIGHT = "理 解 不 能.",
		MAXWELLLOCK = "想 要 解 开 锁 的 钥 匙.",
		MAXWELLTHRONE = "它 不 是 一 个 真 正 的 椅 子..",
		MEAT = "耶! 是 肉!",
		MEATBALLS = "我 能 吃 多 少 次?",
		MEATRACK =
		{
			DONE = "吃 饭 的 时 间!",
			DRYING = "等 一 等..",
			DRYINGINRAIN = "这 和 干 燥 是 完 全 不 同 的.",
			GENERIC = "把 肉 放 在 这. 只 吃 它!",
		},
		MEAT_DRIED = "吃 肉.",
		MERM = "它 们 闻 起 来 没 问 题.",
		MERMHEAD = "这 就 是 你 为 什 么 这 么 臭!",
		MERMHOUSE = "真 臭, 真 丑 的 房 子.",
		MONSTERLASAGNA = "有 些 人 不 喜 欢 它，我 不 介 意.",
		MONSTERMEAT = "味 道 不 一 样, 但 是 很 美 味.",
		MONSTERMEAT_DRIED = "吃 肉.",
		MOSQUITO =
		{
			GENERIC = "笨 蛋 蚊 子.",
			HELD = "又 丑 又 蠢.",
		},
		MOSQUITOSACK = "他 们 偷 了 它.",
		MOUND =
		{
			DUG = "它 是 空 的.",
			GENERIC = "死 了 的 人 和 他 们 的 东 西.",
		},
		NIGHTLIGHT = "奇 怪 的 光.",
		NIGHTMAREFUEL = "装 满 了 灵 魂!",
		NIGHTSWORD = "引 致 死 亡 的 东 西.",
		NITRE = "五 颜 六 色 的 岩 石.",
		ONEMANBAND = "我 只 知 道 如 何 玩 这 些.",
		PANDORASCHEST = "它 为 什 么 有 角?",
		PANFLUTE = "*嘟 嘟 嘟*",
		PAPYRUS = "折 纸!",
		PENGUIN = "鱼 和 鸟!",
		PERD = "晚 饭!",
		PEROGIES = "肉 藏 在 里 面.",
		PETALS = "颜 色 很 多.",
		PETALS_EVIL = "全 都 扭 曲 了.",
		PICKAXE = "把 石 头 打 碎.",
		PIGGYBACK = "扰 乱 了 气 味.",
		PIGHEAD = "真 可 怕..",
		PIGHOUSE =
		{
			FULL = "喂! 我 要 使 用 你 的 洗 澡 间!",
			GENERIC = "我 更 喜 欢 回 到 我 的 城 堡.",
			LIGHTSOUT = "他 们 必 须 知 道 关 于 三 只 小 猪 的 事 情.",
		},
		PIGKING = "一 个 偷 懒 的 王!",
		PIGMAN =
		{
			DEAD = "猪 肉.",
			FOLLOWER = "他 必 须 保 持 上 风.",
			GENERIC = "他 们 不 知 道 洗 澡 吗?",
			GUARD = "他 不 知 道 我 是 个 公 主.",
			WEREPIG = "猪 头 真 坏.",
		},
		PIGSKIN = "这 是 最 坏 的 结 局.",
		PIGTORCH = "他 们 为 此 而 发 疯.",
		PINECONE = 
		{
		    GENERIC = "树 的 宝 宝!",
		    PLANTED = "看 起 来 是 一 个 无 聊 的 小 树.",
		},
		PITCHFORK = "像 一 个 真 正 的 大 叉 子.",
		PLANTMEAT = "素 肉?",
		PLANTMEAT_COOKED = "还 不 是 很 有 说 服 力.",
		PLANT_NORMAL =
		{
			GENERIC = "噢, 我 想 要 肉.",
			GROWING = "它 越 来 越 多 了.",
			READY = "获 得. 蔬 菜.",
			WITHERED = "干 了.. 没 水 分 的 植 物?",
		},
		POMEGRANATE = "嗯? 浆 果 在 里 面?",
		POMEGRANATE_COOKED = "味 道 很 好!",
		POMEGRANATE_SEEDS = "看 起 来 像 浆 果.",
		POOP = "随 地 大 便 是 不 礼 貌 的!",
		PUMPKIN = "耶! 万 圣 节!",
		PUMPKINCOOKIE = "曲 奇 饼!!",
		PUMPKIN_COOKED = "一 个 素 食 主 义 者，不 坏.",
		PUMPKIN_LANTERN = "喔! 真 可 怕.",
		PUMPKIN_SEEDS = "它 长 出 来 的 东 西 可 以 做 饼 干.",
		PURPLEGEM = "感 觉 怪 怪 的.",
		RABBIT =
		{
			GENERIC = "兔 子 先 生.",
			HELD = "这 太 简 单 了.",
		},
		RABBITHOLE = 
		{
			GENERIC = "不 是 一 个 很 好 的 房 子.",
			SPRING = "这 就 是 你 为 什 么 不 用 泥 土 建 造 了.",
		},
		RAINOMETER = "如 果 这 个 表 湿 了, 就 会 下 雨.",
		RATATOUILLE = "啊, 这 是 蔬 菜!",
		RAZOR = "我 不 需 要 剪 头 发.",
		REDGEM = "草 莓 味 的.",
		RED_CAP = "它 对 胃 不 好.",
		RED_CAP_COOKED = "吃 不 出 味 道 来.",
		RED_MUSHROOM =
		{
			GENERIC = "这 是 一 个 蘑 菇.",
			INGROUND = "偷 偷 摸 摸 的 蘑 菇!",
			PICKED = "它 们 会 长 大 吗?",		
		},
		REEDS =
		{
			BURNING = "火!",
			GENERIC = "顶 部 看 起 来 像 香 肠.",
			PICKED = "一 个 不 留.",
		},
        RELIC = 
        {
            GENERIC = "这 是 某 种 东 西.",
            BROKEN = "都 破 坏 了.",
        },
        RUBBLE = "混 乱 的 石 头.",
		RESEARCHLAB = "这 是 发 生 科 学 的 地 方!",
		RESEARCHLAB2 = "两 倍 的!",
		RESEARCHLAB3 = "太 多 了!",
		RESURRECTIONSTATUE = "这 是 现 代 艺 术.",
		RESURRECTIONSTONE = "神 秘 的 岩 石.",
		ROBIN =
		{
			GENERIC = "她 是 一 只 快 乐 的 小 鸟.",
			HELD = "口 袋 里 的 小 鸟!",
		},
		ROBIN_WINTER =
		{
			GENERIC = "那 只 小 鸟 需 要 理 发.",
			HELD = "毛 茸 茸 的.",
		},
		ROBOT_PUPPET = "它 闻 起 来 不 对 劲.",
		ROCK_LIGHT =
		{
			GENERIC = "看 起 来 像 石 头.",
			OUT = "只 是 石 头.",
			LOW = "它 在 变 暗.",
			NORMAL = "不 是 水!"
		},
		ROCKS = "石 头 的 味 道.",
        ROOK = "真 难 看!",
        ROPE = "打 成 结.",
		ROTTENEGG = "我 的 鼻 子 失 灵 了.",
		SANITYROCK =
		{
			ACTIVE = "谁 花 了 这 么 长 时 间 雕 刻 这 个?",
			INACTIVE = "它 退 缩 了?",
		},
		SAPLING =
		{
			BURNING = "火!",
			WITHERED = "它 需 要 喝 一 杯.",
			GENERIC = "它 在 努 力 成 长.",
			PICKED = "振 作 起 来，小 树 苗!",
		},
		SEEDS = "在 那 里 的 某 个 地 方 有 一 棵 树.",
		SEEDS_COOKED = "如 果 没 有 其 它 的 食 物..",
		SEWING_KIT = "缝 纫 课 程 完 成.",
		SHOVEL = "去 挖 宝 藏!",
		SILK = "毛 虫 做 了 件 好 事.",
		SKELETON = "啊! 他 光 着 身 子!",
		SKULLCHEST = "看 起 来 太 糟 了.",
		SMALLBIRD =
		{
			GENERIC = "你 好，小 矮 子.",
			HUNGRY = "你 想 要 些 食 物?",
			STARVING = "饥 饿 的 小 鸟.",
		},
		SMALLMEAT = "只 有 一 点 点 的 肉.",
		SMALLMEAT_DRIED = "小 点 心.",
		SPEAR = "我 不 再 是 点 心!",
		SPIDER =
		{
			DEAD = "活 该.",
			GENERIC = "混 蛋 虫 子.",
			SLEEPING = "还 是 不 可 爱.",
		},
		SPIDERDEN = "可 怕 虫 子 的 房 子.",
		SPIDEREGGSACK = "要 小 心 的 拿 着",
		SPIDERGLAND = "有 点 讨 厌.",
		SPIDERHAT = "我 不 会 穿 它 的.",
		SPIDERQUEEN = "虫子，虫子!",
		SPIDER_WARRIOR =
		{
			DEAD = "不 好 对 付 的 虫 子.",
			GENERIC = "更 加 肮 脏 的.",
			SLEEPING = "虫 子 在 午 睡.",
		},
		SPOILED_FOOD = "我 非 常 讨 厌 腐 烂 的 食 物!",
		STATUEHARP = "蹩 脚 的!",
		STATUEMAXWELL = "这 个 雕 像.",
		STINGER = "保 护 屁 股 的.",
		STRAWHAT = "夏 天 穿 的.",
		SUNKBOAT = "不 安 全 的 海 洋.",
		SWEATERVEST = "幸 存 者 的 最 新 潮 流.",
		TAFFY = "糖 果! 糖.........果!",
		TALLBIRD = "看 起 来 不 像 一 个 朋 友.",
		TALLBIRDEGG = "哦, 这 是 什 么 点 心.",
		TALLBIRDEGG_COOKED = "早 餐!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "一 定 很 冷.",
			GENERIC = "容 纳 着 一 只 宠 物!",
			HOT = "它 现 在 很 热.",
			LONG = "他 在 那 里 做 什 么?",
			SHORT = "出 来 吧!",
		},
		TALLBIRDNEST =
		{
			GENERIC = "那 只 鸟 做 的 它.",
			PICKED = "没 蛋 了.",
		},
		TEENBIRD =
		{
			GENERIC = "越 来 越 多 的 小 鸟.",
			HUNGRY = "你 想 要 更 多 的 食 物 吗?",
			STARVING = "好 的, 我 给 你!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我 可 以 离 开 了!",
			GENERIC = "它 做 的? 真 的 吗?",
			LOCKED = "都 锁 起 来.",
			PARTIAL = "做.... 什么事呢...",
		},
		TELEPORTATO_BOX = "嗯..",
		TELEPORTATO_CRANK = "垃 圾?",
		TELEPORTATO_POTATO = "发 条 植 物?",
		TELEPORTATO_RING = "珠 宝?",
		TENT = "我 的 房 子!",
		TENTACLE = "紫 色 的 东 西 不 好.",
		TENTACLESPOTS = "咳, 它 的 毛 皮!",
		TENTACLESPIKE = "粉 碎!",
		TENTACLE_PILLAR = "这 是 树 吗?",
		TENTACLE_PILLAR_ARM = "它 们 来 了 还 打 招 呼.",
		TENTACLE_GARDEN = "我 可 以 听 见 它 们 在 底 下.",
		TOPHAT = "如 果 没 有 皇 冠 的 话 只 有 这 个 最 好.",
		TORCH = "虽 然 我 可 以 闻 到，但 是 能 看 见 真 是 太 好 了.",
		TRAP = "用 匣 子 和 棍 子 敲 打 兔 子.",
		TRAP_TEETH = "太 破 了.",
		TRAP_TEETH_MAXWELL = "有 人 试 图 掩 盖 它.",
		TREASURECHEST = "这 是 我 的 东 西!",
		TRINKET_1 = "融 化 的 糖 果.",
		TRINKET_10 = "什 么? 假 牙?",
		TRINKET_11 = "一 个 机 器 人.",
		TRINKET_12 = "这 真 让 人 恶 心.",
		TRINKET_2 = "它 不 会 制 造 噪 音.",
		TRINKET_3 = "结 非 常 有 用.",
		TRINKET_4 = "粘 土 和 油 漆.",
		TRINKET_5 = "火 箭 是 什 么?",
		TRINKET_6 = "金 属 做 的 绳 子.",
		TRINKET_7 = "我 老 了 之 后 玩 的 玩 具.",
		TRINKET_8 = "洗 澡 就 好 了.",
		TRINKET_9 = "没 有 两 个 是 相 同 的.",
		TRUNKVEST_SUMMER = "暖 和 又 防 雨.",
		TRUNKVEST_WINTER = "可 以 保 暖 一 整 天.",
		TRUNK_COOKED = "这 有 点 奇 怪.",
		TRUNK_SUMMER = "这 可 能 有 用.",
		TRUNK_WINTER = "有 很 多 的 毛 皮.",
		UMBRELLA = "遮 雨.",
		WAFFLES = "我 会 吃 了 你!",
		WALL_HAY = "不 太 结 实 的 墙.",
		WALL_HAY_ITEM = "基 础.",
		WALL_STONE = "像 一 个 城 堡!",
		WALL_STONE_ITEM = "移 动 墙.",
		WALL_RUINS = "上 次 做 的.",
		WALL_RUINS_ITEM = "随 身 携 带 的 硬 东 西!",
		WALL_WOOD = "木 片 还 有 用.",
		WALL_WOOD_ITEM = "很 传 统 的.",
		WALRUS = "我 对 你 做 过 什 么 吗?",
		WALRUSHAT = "现 在 真 正 的 猎 人 是 谁?",
		WALRUS_CAMP =
		{
			EMPTY = "我 不 想 靠 得 太 近.",
			GENERIC = "冰 做 的 房 子? 唔.",
		},
		WALRUS_TUSK = "我 可 以 变 成 剑 齿 虎 吗?",
		WASPHIVE = "那 里 的 蜜 蜂 一 点 也 不 友 好.",
		WETGOOP = "和 食 物 相 反 的 东 西!",
		WINTERHAT = "可 以 让 我 的 耳 朵 保 持 温 暖.",
		WINTEROMETER = "它 应 该 待 在 中 间.",
		WORMHOLE =
		{
			GENERIC = "毛 茸 茸 的 地 面.",
			OPEN = "这 是 有 多 懒 啊.",
		},
		ACCOMPLISHMENT_SHRINE = "它 有 什 么 企 图?",        		
	},
	DESCRIBE_TOODARK = "黑 咕 隆 咚 的!",
	DESCRIBE_SMOLDERING = "它 在 吸 烟!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "呃. 嘎 嘣 脆.",
	},
}
